Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -252,7 +252,11 @@ jobs:
         uses: hashicorp/actions-docker-build@v2
         with:
           smoke_test: |
-            docker run "${IMAGE_NAME}"
+            TEST_VERSION="$(docker run "${IMAGE_NAME}" --version)"
+            if [ "${TEST_VERSION}" != "${{ env.product_version }}" ]; then
+              printf "fail: container smoke test, got=%q want=%q\n" "${TEST_VERSION}" "${{ env.product_version }}"
+              exit 1
+            fi
             printf "ok: container smoke test\n"
           pkg_name: ${{ env.PKG_NAME }}_${{ env.product_version }}
           bin_name: ${{ env.PKG_NAME }}
